# Generated by Django 4.1.4 on 2023-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='chips_in_action',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
