# Generated by Django 4.1.4 on 2023-01-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='table_name',
            field=models.CharField(default='table', max_length=100),
        ),
    ]
