# Generated by Django 4.1.4 on 2023-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_useraccount_chips_in_action_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='config',
            field=models.JSONField(default={'ante': 0, 'max_buyin': 500, 'min_buyin': 100, 'small_blind': 20}),
        ),
    ]
