# Generated by Django 4.1.4 on 2023-01-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gametable_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='moves_log',
            field=models.JSONField(default={}),
        ),
    ]
