# Generated by Django 4.1.4 on 2023-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gametable_moves_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='table_name',
            field=models.CharField(default='table', max_length=100, unique=True),
        ),
    ]
