# Generated by Django 4.1.4 on 2023-04-03 13:16

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gametable_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='config',
            field=models.JSONField(default=game.models.GameTable.default_config),
        ),
    ]
