# Generated by Django 4.1.4 on 2023-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gametable_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='table_name',
            field=models.CharField(default='table', max_length=100),
        ),
    ]
