# Generated by Django 4.1.4 on 2023-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gametable_moves_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(verbose_name=dict)),
            ],
        ),
        migrations.AddField(
            model_name='gametable',
            name='games_log',
            field=models.JSONField(default=dict),
        ),
    ]
