# Generated by Django 4.1.4 on 2023-01-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_jsontest_gametable_games_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_name', models.CharField(default='p1', max_length=100)),
                ('p2_name', models.CharField(default='p2', max_length=100)),
                ('log', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='gametable',
            name='games_log',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jsontest',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jsontest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
