# Generated by Django 4.1.4 on 2023-01-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamelog_alter_gametable_games_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='games_log',
        ),
    ]
