# Generated by Django 4.1.4 on 2023-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gamelog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='table',
            field=models.CharField(default='', max_length=100),
        ),
    ]
