# Generated by Django 4.1.4 on 2023-01-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_gamelog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='table',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
