# Generated by Django 4.1.4 on 2023-01-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gamelog_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonTest',
        ),
    ]
