# Generated by Django 4.1.4 on 2023-01-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_delete_jsontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='moves_log',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='player1_cards',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='player2_cards',
        ),
    ]
