# Generated by Django 4.1.4 on 2023-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gametable_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='to_move',
            field=models.CharField(default='p1', max_length=100),
        ),
    ]
