# Generated by Django 4.1.4 on 2023-01-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_gametable_to_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='p1_status',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='p2_status',
        ),
    ]
