# Generated by Django 4.1.4 on 2023-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_gametable_p1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='card1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametable',
            name='card2',
            field=models.IntegerField(default=0),
        ),
    ]
