# Generated by Django 4.1.4 on 2023-01-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_gametable_card1_gametable_card2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='moves_made',
            field=models.IntegerField(default=0),
        ),
    ]
