# Generated by Django 4.1.4 on 2023-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_gametable_moves_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
