# Generated by Django 4.1.4 on 2023-02-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_remove_gametable_card1_remove_gametable_card2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='table_state',
            field=models.CharField(choices=[('ENDED', 'ended'), ('PREFLOP', 'preflop'), ('FLOP', 'flop'), ('TURN', 'turn'), ('RIVER', 'river')], default='ENDED', max_length=10),
        ),
    ]
