# Generated by Django 4.1.4 on 2023-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_gametable_table_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='to_move',
            field=models.IntegerField(default=1),
        ),
    ]
