# Generated by Django 4.1.4 on 2023-02-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_gametable_to_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='table_state',
            field=models.IntegerField(choices=[(0, 'Ended'), (1, 'Preflop'), (2, 'Flop'), (3, 'Turn'), (4, 'River')], default=0),
        ),
    ]
