# Generated by Django 4.1.4 on 2023-02-03 12:01

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_gametable_available_commands_gametable_last_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='bets',
            field=models.JSONField(default=game.models.GameTable.init_bets),
        ),
        migrations.AddField(
            model_name='gametable',
            name='pots',
            field=models.JSONField(default=list),
        ),
    ]
