# Generated by Django 4.1.4 on 2023-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_gametable_bets_gametable_pots'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='has_folded',
            field=models.JSONField(default=dict),
        ),
    ]
