# Generated by Django 4.1.4 on 2023-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_gametable_has_folded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='move_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='move_queue',
            field=models.JSONField(default=dict),
        ),
    ]
