# Generated by Django 4.1.4 on 2023-02-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_remove_gametable_has_folded_remove_gametable_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='deck',
            field=models.JSONField(default=list),
        ),
    ]
