# Generated by Django 4.1.4 on 2023-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_gametable_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='community_cards',
            field=models.JSONField(default=list),
        ),
    ]
