# Generated by Django 4.1.4 on 2023-02-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='available_commands',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='last_bet',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
