# Generated by Django 4.1.4 on 2023-02-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_alter_gametable_available_commands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='available_commands',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='last_bet',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
