# Generated by Django 4.1.4 on 2023-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_alter_gametable_available_commands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='game.player'),
        ),
    ]
