# Generated by Django 4.1.4 on 2023-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_alter_gametable_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='community_cards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='pots',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
