# Generated by Django 4.1.4 on 2023-03-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_alter_gametable_community_cards_alter_gametable_pots'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='winners',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='table_state',
            field=models.IntegerField(choices=[(0, 'Ended'), (1, 'Preflop'), (2, 'Flop'), (3, 'Turn'), (4, 'River'), (5, 'Show Down'), (6, 'No Show Down')], default=0),
        ),
    ]
