# Generated by Django 4.1.4 on 2023-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
